services:
  backend_rds:
    image: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${AWS_ECR_RDS}:${IMAGE_TAG}"
    ports:
      - "5432:5432"
    env_file:
      - .env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first

  backend_redis:
    image: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${AWS_ECR_REDIS}:${IMAGE_TAG}"
    ports:
      - "6379:6379"
    env_file:
      - .env
    volumes:
      - ./redis_data:/data