services:
  # backend_redis:
  #   image: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/redis:${IMAGE_TAG}"
  #   ports:
  #     - "6379:6379"
  #   env_file:
  #     - .env
  #   volumes:
  #     - .:/app

  backend_rds:
    image: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/rds:${IMAGE_TAG}"
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - .:/app

  # web:
  #   image: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/web:${IMAGE_TAG}"
  #   ports:
  #     - "80:80"
  #   env_file:
  #     - .env
  #   volumes:
  #     - .:/app
