services:
  backend_rds:
    image: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/rds_prod:${IMAGE_TAG}"
    ports:
      - "8000:8000"
    env_file:
      - .env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first

  backend_redis:
    image: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/redis_prod:${IMAGE_TAG}"
    ports:
      - "8001:8001"
    env_file:
      - .env
    volumes:
      - ./redis_data:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
