
services:
  backend_rds:
    image: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/dev_rds:${IMAGE_TAG}"
    ports:
      - "5432:5432"
    env_file:
      - .env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  backend_redis:
    image: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/dev_redis:${IMAGE_TAG}"
    ports:
      - "6379:6379"
    env_file:
      - .env
    volumes:
      - ./redis_data:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure