services:
  backend_redis:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev # Якщо потрібно
    image: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/redis:${IMAGE_TAG}"
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app

  backend_rds:
    build:
      context: .  # Build context set to current directory
      dockerfile: Dockerfile
      target: dev
    image: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/rds:${IMAGE_TAG}"
    ports:
      - "7000:7000"  # Correct Django port
    env_file:
      - .env
    volumes:
      - .:/app
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first

volumes:
  postgres_data:
