services:
  backend_redis:
    image: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/redis:${IMAGE_TAG}"
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app

  backend_rds:
    image: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/rds:${IMAGE_TAG}"
    ports:
      - "4000:4000"
    env_file:
      - .env
    volumes:
      - .:/app

  web:
    image: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/web:${IMAGE_TAG}"
    ports:
      - "80:80"
    env_file:
      - .env
    volumes:
      - .:/app
