services:
  web:
    image: "public.ecr.aws/b7r1g3n1/rds:076394671eb62cfd8ddad10be11869429e081084"
    ports:
      - "80:80"
    env_file:
      - .env
    volumes:
      - .:/app
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first

volumes:
  postgres_data:
