# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set environment variables
#ENV PYTHONDONTWRITEBYTECODE 1
#ENV PYTHONUNBUFFERED 1

# Set the working directory
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt /app/

# Install the dependencies
RUN pip install --upgrade pip && pip install -r /app/requirements.txt

# Copy the rest of the application code into the container
COPY . /app/

# Expose port 80
EXPOSE 6379

# Run the Flask app
CMD ["python", "/app/backend_redis/core/views.py"]